name: example
description:  Demonstrates how to use the time_picker_spinner_pop_up package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


  time_picker_spinner_pop_up:
    path: ../

dependency_overrides:
  intl: 0.20.0

flutter:
  uses-material-design: true

